name: myenv
channels:
  - defaults
dependencies:
  - matplotlib=3.3.4
  - joblib=1.1.1
  - numpy=1.17.3
  - pandas=1.1.5
  - scipy=1.3.2
  - seaborn=0.12.1
  - streamlit=1.11.0
  - threadpoolctl=2.0.0
